# Generated by Django 3.1.1 on 2020-11-05 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='car.jpg', upload_to='car_images')),
                ('no_year', models.IntegerField()),
                ('ex_price', models.FloatField()),
                ('kms_driven', models.IntegerField()),
                ('no_owners', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=25)),
                ('engine', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('trasmission', models.CharField(max_length=25)),
                ('seller_type', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
