# Generated by Django 3.1.1 on 2020-11-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='no_year',
            new_name='purchase_year',
        ),
    ]
