# Generated by Django 3.1.1 on 2020-11-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201105_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='trasmission',
            new_name='transmission',
        ),
    ]
