# Generated by Django 3.1.1 on 2020-11-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201105_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='selling_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
