# Generated by Django 3.1.1 on 2020-11-06 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201106_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
